---

- hosts: localhost
  gather_facts: False
  tasks:
    - name: create DigitalOcean SSH key
      digital_ocean: >
          command=ssh
          name=travisci
          ssh_pub_key="{{ lookup('file', 'loyo.pub') }}"
          client_id={{ client_id }}
          api_key={{ api_key_password }}
      register: loyokey

    - name: create DigitalOcean droplets to deploy cluster on (1 monitor + 2 master + 4 slave droplets)
      digital_ocean: >
          name={{ item }}
          unique_name=yes
          ssh_key_ids="{{ loyokey.ssh_key.id }}"
          client_id={{ client_id }}
          api_key={{ api_key_password }}
          size_id=62
          region_id=9
          image_id=6918990
          wait=no
      with_items:
        - monitor01
        - hmaster01
        - hmaster02
        - hslave01
        - hslave02

    - name: create DigitalOcean droplets to deploy cluster on (1 monitor + 2 master + 4 slave droplets)
      digital_ocean: >
          name={{ item }}
          unique_name=yes
          ssh_key_ids="{{ loyokey.ssh_key.id }}"
          client_id={{ client_id }}
          api_key={{ api_key_password }}
          size_id=62
          region_id=9
          image_id=6918990
      register: hosts
      with_items:
        - monitor01
        - hmaster01
        - hmaster02
        - hslave01
        - hslave02

    - name: delete previous tracking files
      file: path={{ item }} state=absent
      with_items:
        - destroy_cluster.sh
        - etc_hosts

    - name: create tracking files
      file: path={{ item }} state=touch
      with_items:
        - destroy_cluster.sh
        - etc_hosts

    - name: create delete script
      lineinfile: create=yes dest=destroy_cluster.sh line="wget -qO- https://api.digitalocean.com/droplets/{{ item.droplet.id }}/destroy/\?client_id\={{ client_id }}\&api_key\={{ api_key_password }}" mode=755
      with_items: hosts.results

    - name: dump hosts to etc_hosts
      lineinfile: dest=etc_hosts line="{{ item.droplet.ip_address }} {{ item.droplet.name }}"
      with_items: hosts.results